// GENERATED FILE. Do not edit by hand.
// Run: dart run tool/chart_sources/generate.dart
//
// The source every gallery card copies, read out of
// lib/charts/specimens_*.dart so that what a reader copies is
// what this package compiles.
library;

const Map<String, String> chartSources = <String, String>{
  'chart-area-default':
      'Widget areaDefault(ChartInk ink) => plot(\n  ink.desktop,\n  CartesianChart(\n    data: monthsDesktop,\n    // Plot maths, not the 8-point scale: recharts\' own margin box.\n    margin: const ChartMargin(left: 12, right: 12),\n    grid: const ChartGrid(vertical: false),\n    xAxis: monthAxis(),\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      indicator: ChartIndicator.line,\n    ),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.area,\n        dataKey: \'desktop\',\n        curve: CurveType.natural,\n        fill: ink.slot(1),\n        fillOpacity: 0.4,\n        stroke: ink.slot(1),\n      ),\n    ],\n  ),\n);',
  'chart-area-linear':
      'Widget areaLinear(ChartInk ink) => plot(\n  ink.desktop,\n  CartesianChart(\n    data: monthsDesktop,\n    margin: const ChartMargin(left: 12, right: 12),\n    grid: const ChartGrid(vertical: false),\n    xAxis: monthAxis(),\n    tooltip: const ChartTooltipSpec(cursor: false, hideLabel: true),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.area,\n        dataKey: \'desktop\',\n        fill: ink.slot(1),\n        fillOpacity: 0.4,\n        stroke: ink.slot(1),\n      ),\n    ],\n  ),\n);',
  'chart-area-step':
      'Widget areaStep(ChartInk ink) => plot(\n  ChartConfig(<String, ChartSeries>{\n    \'desktop\': ChartSeries(\n      label: \'Desktop\',\n      color: ink.slot(1),\n      icon: (BuildContext context) =>\n          const Icon.lucide(Lucide.activity, size: IconSize.xs),\n    ),\n  }),\n  CartesianChart(\n    data: monthsDesktop,\n    margin: const ChartMargin(left: 12, right: 12),\n    grid: const ChartGrid(vertical: false),\n    xAxis: monthAxis(),\n    tooltip: const ChartTooltipSpec(cursor: false, hideLabel: true),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.area,\n        dataKey: \'desktop\',\n        curve: CurveType.step,\n        fill: ink.slot(1),\n        fillOpacity: 0.4,\n        stroke: ink.slot(1),\n      ),\n    ],\n  ),\n);',
  'chart-area-stacked':
      'Widget areaStacked(ChartInk ink) => plot(\n  ink.desktopMobile,\n  CartesianChart(\n    data: monthsDesktopMobile,\n    margin: const ChartMargin(left: 12, right: 12),\n    grid: const ChartGrid(vertical: false),\n    xAxis: monthAxis(),\n    tooltip: const ChartTooltipSpec(cursor: false),\n    series: _stackedAreas(ink),\n  ),\n);',
  'chart-area-stacked-expand':
      'Widget areaStackedExpand(ChartInk ink) => plot(\n  ink.desktopMobile.plus(<String, ChartSeries>{\n    \'other\': ChartSeries(label: \'Other\', color: ink.slot(3)),\n  }),\n  CartesianChart(\n    data: _areaExpandData,\n    margin: const ChartMargin(left: 12, right: 12, top: 12),\n    stackOffsetExpand: true,\n    grid: const ChartGrid(vertical: false),\n    xAxis: monthAxis(),\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      indicator: ChartIndicator.line,\n    ),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.area,\n        dataKey: \'other\',\n        curve: CurveType.natural,\n        stackId: \'a\',\n        fill: ink.slot(3),\n        fillOpacity: 0.1,\n        stroke: ink.slot(3),\n      ),\n      ..._stackedAreas(ink),\n    ],\n  ),\n);',
  'chart-area-legend':
      'Widget areaLegend(ChartInk ink) => plot(\n  ink.desktopMobile,\n  CartesianChart(\n    data: monthsDesktopMobile,\n    margin: const ChartMargin(left: 12, right: 12),\n    grid: const ChartGrid(vertical: false),\n    xAxis: monthAxis(),\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      indicator: ChartIndicator.line,\n    ),\n    legend: const ChartLegendSpec(),\n    series: _stackedAreas(ink),\n  ),\n);',
  'chart-area-icons':
      'Widget areaIcons(ChartInk ink) => plot(\n  ChartConfig(<String, ChartSeries>{\n    \'desktop\': ChartSeries(\n      label: \'Desktop\',\n      color: ink.slot(1),\n      icon: (BuildContext context) =>\n          const Icon.lucide(Lucide.trendingDown, size: IconSize.sm),\n    ),\n    \'mobile\': ChartSeries(\n      label: \'Mobile\',\n      color: ink.slot(2),\n      icon: (BuildContext context) =>\n          const Icon.lucide(Lucide.trendingUp, size: IconSize.sm),\n    ),\n  }),\n  CartesianChart(\n    data: monthsDesktopMobile,\n    margin: const ChartMargin(left: 12, right: 12),\n    grid: const ChartGrid(vertical: false),\n    xAxis: monthAxis(),\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      indicator: ChartIndicator.line,\n    ),\n    legend: const ChartLegendSpec(),\n    series: _stackedAreas(ink),\n  ),\n);',
  'chart-area-gradient':
      'Widget areaGradient(ChartInk ink) => plot(\n  ink.desktopMobile,\n  CartesianChart(\n    data: monthsDesktopMobile,\n    margin: const ChartMargin(left: 12, right: 12),\n    grid: const ChartGrid(vertical: false),\n    xAxis: monthAxis(),\n    tooltip: const ChartTooltipSpec(cursor: false),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.area,\n        dataKey: \'mobile\',\n        curve: CurveType.natural,\n        stackId: \'a\',\n        gradient: _gradientFor(ink.slot(2), opacity: 0.4),\n        stroke: ink.slot(2),\n      ),\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.area,\n        dataKey: \'desktop\',\n        curve: CurveType.natural,\n        stackId: \'a\',\n        gradient: _gradientFor(ink.slot(1), opacity: 0.4),\n        stroke: ink.slot(1),\n      ),\n    ],\n  ),\n);',
  'chart-area-axes':
      'Widget areaAxes(ChartInk ink) => plot(\n  ink.desktopMobile,\n  CartesianChart(\n    data: monthsDesktopMobile,\n    margin: const ChartMargin(left: -20, right: 12),\n    grid: const ChartGrid(vertical: false),\n    xAxis: monthAxis(),\n    yAxis: const ChartAxis(\n      type: ChartAxisType.number,\n      tickLine: false,\n      axisLine: false,\n      tickMargin: 8,\n      tickCount: 3,\n    ),\n    tooltip: const ChartTooltipSpec(cursor: false),\n    series: _stackedAreas(ink),\n  ),\n);',
  'chart-area-interactive':
      'Widget areaInteractive(BuildContext context, ChartInk ink) => plot(\n  ink.desktopMobile.plus(<String, ChartSeries>{\n    \'visitors\': const ChartSeries(label: \'Visitors\'),\n  }),\n  CartesianChart(\n    data: AreaInteractive.filtered(AreaInteractiveRange.of(context)),\n    grid: const ChartGrid(vertical: false),\n    xAxis: const ChartAxis(\n      dataKey: \'date\',\n      tickLine: false,\n      axisLine: false,\n      tickMargin: 8,\n      minTickGap: 32,\n      tickFormatter: shortDate,\n    ),\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      labelFormatter: _shortDateLabel,\n    ),\n    legend: const ChartLegendSpec(),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.area,\n        dataKey: \'mobile\',\n        curve: CurveType.natural,\n        stackId: \'a\',\n        gradient: _gradientFor(ink.slot(2)),\n        stroke: ink.slot(2),\n      ),\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.area,\n        dataKey: \'desktop\',\n        curve: CurveType.natural,\n        stackId: \'a\',\n        gradient: _gradientFor(ink.slot(1)),\n        stroke: ink.slot(1),\n      ),\n    ],\n  ),\n);',
  'chart-bar-default':
      'Widget barDefault(ChartInk ink) => plot(\n  ink.desktop,\n  CartesianChart(\n    data: monthsDesktop,\n    grid: const ChartGrid(vertical: false),\n    xAxis: _barMonthAxis,\n    tooltip: const ChartTooltipSpec(cursor: false, hideLabel: true),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.bar,\n        dataKey: \'desktop\',\n        fill: ink.slot(1),\n        radii: radiiAll,\n      ),\n    ],\n  ),\n);',
  'chart-bar-horizontal':
      'Widget barHorizontal(ChartInk ink) => plot(\n  ink.desktop,\n  CartesianChart(\n    data: monthsDesktop,\n    layout: ChartLayout.vertical,\n    margin: const ChartMargin(left: -20),\n    xAxis: const ChartAxis(\n      type: ChartAxisType.number,\n      dataKey: \'desktop\',\n      hide: true,\n    ),\n    yAxis: const ChartAxis(\n      dataKey: \'month\',\n      tickLine: false,\n      axisLine: false,\n      tickMargin: 10,\n      tickFormatter: month3,\n    ),\n    tooltip: const ChartTooltipSpec(cursor: false, hideLabel: true),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.bar,\n        dataKey: \'desktop\',\n        fill: ink.slot(1),\n        radii: radiiAll,\n      ),\n    ],\n  ),\n);',
  'chart-bar-multiple':
      'Widget barMultiple(ChartInk ink) => plot(\n  ink.desktopMobile,\n  CartesianChart(\n    data: monthsDesktopMobile,\n    grid: const ChartGrid(vertical: false),\n    xAxis: _barMonthAxis,\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      indicator: ChartIndicator.dashed,\n    ),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.bar,\n        dataKey: \'desktop\',\n        fill: ink.slot(1),\n        radii: radiiAll,\n      ),\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.bar,\n        dataKey: \'mobile\',\n        fill: ink.slot(2),\n        radii: radiiAll,\n      ),\n    ],\n  ),\n);',
  'chart-bar-stacked':
      'Widget barStacked(ChartInk ink) => plot(\n  ink.desktopMobile,\n  CartesianChart(\n    data: monthsDesktopMobile,\n    grid: const ChartGrid(vertical: false),\n    xAxis: _barMonthAxis,\n    tooltip: const ChartTooltipSpec(hideLabel: true),\n    legend: const ChartLegendSpec(),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.bar,\n        dataKey: \'desktop\',\n        stackId: \'a\',\n        fill: ink.slot(1),\n        radii: radiiBottom,\n      ),\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.bar,\n        dataKey: \'mobile\',\n        stackId: \'a\',\n        fill: ink.slot(2),\n        radii: radiiTop,\n      ),\n    ],\n  ),\n);',
  'chart-bar-label':
      'Widget barLabel(ChartInk ink, ThemeTokens theme) => plot(\n  ink.desktop,\n  CartesianChart(\n    data: monthsDesktop,\n    margin: const ChartMargin(top: 20),\n    grid: const ChartGrid(vertical: false),\n    xAxis: _barMonthAxis,\n    tooltip: const ChartTooltipSpec(cursor: false, hideLabel: true),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.bar,\n        dataKey: \'desktop\',\n        fill: ink.slot(1),\n        radii: radiiAll,\n        labels: <ChartLabelList>[\n          ChartLabelList(offset: 12, color: theme.foreground),\n        ],\n      ),\n    ],\n  ),\n);',
  'chart-bar-label-custom':
      'Widget barLabelCustom(ChartInk ink, ThemeTokens theme) => plot(\n  ink.desktop,\n  CartesianChart(\n    data: monthsDesktop,\n    layout: ChartLayout.vertical,\n    margin: const ChartMargin(right: 16),\n    grid: const ChartGrid(horizontal: false),\n    yAxis: const ChartAxis(\n      dataKey: \'month\',\n      tickLine: false,\n      axisLine: false,\n      hide: true,\n    ),\n    xAxis: const ChartAxis(\n      dataKey: \'desktop\',\n      type: ChartAxisType.number,\n      hide: true,\n    ),\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      indicator: ChartIndicator.line,\n    ),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.bar,\n        dataKey: \'desktop\',\n        fill: ink.slot(1),\n        radii: radiiAll,\n        labels: <ChartLabelList>[\n          ChartLabelList(\n            dataKey: \'month\',\n            position: ChartLabelPosition.insideLeft,\n            offset: 8,\n            color: theme.background,\n          ),\n          ChartLabelList(\n            dataKey: \'desktop\',\n            position: ChartLabelPosition.right,\n            offset: 8,\n            color: theme.foreground,\n          ),\n        ],\n      ),\n    ],\n  ),\n);',
  'chart-bar-mixed':
      'Widget barMixed(ChartInk ink) => plot(\n  ink.browser,\n  CartesianChart(\n    data: browsers,\n    layout: ChartLayout.vertical,\n    margin: const ChartMargin(left: 0),\n    yAxis: ChartAxis(\n      dataKey: \'browser\',\n      tickLine: false,\n      axisLine: false,\n      tickMargin: 10,\n      tickFormatter: (Object? v) => browserLabel(\'\$v\'),\n    ),\n    xAxis: const ChartAxis(\n      dataKey: \'visitors\',\n      type: ChartAxisType.number,\n      hide: true,\n    ),\n    tooltip: const ChartTooltipSpec(cursor: false, hideLabel: true),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.bar,\n        dataKey: \'visitors\',\n        radii: radiiAll,\n        cellFills: <Color>[\n          for (final Map<String, Object?> row in browsers) ink.ofRow(row),\n        ],\n      ),\n    ],\n  ),\n);',
  'chart-bar-active':
      'Widget barActive(ChartInk ink) => plot(\n  ink.browser,\n  CartesianChart(\n    data: _barActiveData,\n    grid: const ChartGrid(vertical: false),\n    xAxis: ChartAxis(\n      dataKey: \'browser\',\n      tickLine: false,\n      axisLine: false,\n      tickMargin: 10,\n      tickFormatter: (Object? v) => browserLabel(\'\$v\'),\n    ),\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      defaultIndex: 2,\n      hideLabel: true,\n    ),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.bar,\n        dataKey: \'visitors\',\n        radii: radiiAll,\n        cellFills: <Color>[\n          for (final Map<String, Object?> row in _barActiveData) ink.ofRow(row),\n        ],\n      ),\n    ],\n  ),\n);',
  'chart-bar-negative':
      'Widget barNegative(ChartInk ink, ThemeTokens theme) => plot(\n  ChartConfig(<String, ChartSeries>{\n    \'visitors\': const ChartSeries(label: \'Visitors\'),\n  }),\n  CartesianChart(\n    data: _barNegativeData,\n    grid: const ChartGrid(vertical: false),\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      hideLabel: true,\n      hideIndicator: true,\n    ),\n    series: <ChartSeriesSpec>[\n      ChartSeriesSpec(\n        kind: ChartSeriesKind.bar,\n        dataKey: \'visitors\',\n        cellFills: <Color>[\n          for (final Map<String, Object?> row in _barNegativeData)\n            (row[\'visitors\']! as num) > 0 ? ink.slot(1) : ink.slot(2),\n        ],\n        labels: <ChartLabelList>[\n          // No explicit fill in the registry means recharts\' own untokenised\n          // grey paints the month labels: the same class of failure\n          // `ui/chart.tsx` measured on the axis ticks. `fill-foreground`\n          // closes it.\n          ChartLabelList(dataKey: \'month\', color: theme.foreground),\n        ],\n      ),\n    ],\n  ),\n);',
  'chart-bar-interactive':
      'Widget barInteractive(BuildContext context, ChartInk ink) {\n  final String active = SeriesScope.of(context);\n  return plot(\n    ink.desktopMobile.plus(<String, ChartSeries>{\n      \'views\': const ChartSeries(label: \'Page Views\'),\n    }),\n    CartesianChart(\n      data: dailyVisits,\n      margin: const ChartMargin(left: 12, right: 12),\n      grid: const ChartGrid(vertical: false),\n      xAxis: const ChartAxis(\n        dataKey: \'date\',\n        tickLine: false,\n        axisLine: false,\n        tickMargin: 8,\n        minTickGap: 32,\n        tickFormatter: shortDate,\n      ),\n      tooltip: const ChartTooltipSpec(\n        nameKey: \'views\',\n        labelFormatter: shortDateYearLabel,\n      ),\n      series: <ChartSeriesSpec>[\n        ChartSeriesSpec(\n          kind: ChartSeriesKind.bar,\n          dataKey: active,\n          fill: seriesColour(ink, active),\n        ),\n      ],\n    ),\n  );\n}',
  'chart-line-default':
      'Widget lineDefault(ChartInk ink) => lineChart(\n  ink.desktop,\n  monthsDesktop,\n  <ChartSeriesSpec>[_lineSeries(ink.slot(1), \'desktop\', CurveType.natural)],\n  xAxis: monthAxis(),\n);',
  'chart-line-linear':
      'Widget lineLinear(ChartInk ink) => lineChart(\n  ink.desktop,\n  monthsDesktop,\n  <ChartSeriesSpec>[_lineSeries(ink.slot(1), \'desktop\', CurveType.linear)],\n  xAxis: monthAxis(),\n);',
  'chart-line-step':
      'Widget lineStep(ChartInk ink) => lineChart(\n  ink.desktop,\n  monthsDesktop,\n  <ChartSeriesSpec>[_lineSeries(ink.slot(1), \'desktop\', CurveType.step)],\n  xAxis: monthAxis(),\n);',
  'chart-line-multiple':
      'Widget lineMultiple(ChartInk ink) => lineChart(\n  ink.desktopMobile,\n  monthsDesktopMobile,\n  <ChartSeriesSpec>[\n    _lineSeries(ink.slot(1), \'desktop\', CurveType.monotone),\n    _lineSeries(ink.slot(2), \'mobile\', CurveType.monotone),\n  ],\n  xAxis: monthAxis(),\n  tooltip: const ChartTooltipSpec(),\n);',
  'chart-line-dots':
      'Widget lineDots(ChartInk ink) =>\n    lineChart(ink.desktopMobile, monthsDesktopMobile, <ChartSeriesSpec>[\n      _lineSeries(\n        ink.slot(1),\n        \'desktop\',\n        CurveType.natural,\n        dot: ChartDot(fill: ink.slot(1)),\n      ),\n    ], xAxis: monthAxis());',
  'chart-line-dots-custom':
      'Widget lineDotsCustom(ChartInk ink, ThemeTokens theme) =>\n    lineChart(ink.desktopMobile, monthsDesktopMobile, <ChartSeriesSpec>[\n      _lineSeries(\n        ink.slot(1),\n        \'desktop\',\n        CurveType.natural,\n        dot: ChartDot(\n          radius: Icon.pxFor(IconSize.xl) / 2,\n          fill: theme.background,\n          stroke: ink.slot(1),\n        ),\n      ),\n    ], xAxis: monthAxis());',
  'chart-line-dots-colors':
      'Widget lineDotsColors(ChartInk ink) => lineChart(\n  ink.browser,\n  browsers,\n  <ChartSeriesSpec>[\n    ChartSeriesSpec(\n      kind: ChartSeriesKind.line,\n      dataKey: \'visitors\',\n      curve: CurveType.natural,\n      // `visitors` is the value key and carries no colour of its own, so\n      // the stroke is the plain `--color-chart-2` the registry\'s config\n      // resolves to, not a lookup through it.\n      stroke: ink.slot(2),\n      strokeWidth: 2,\n      dot: const ChartDot(radius: 5),\n      cellFills: <Color>[\n        for (final Map<String, Object?> row in browsers) ink.ofRow(row),\n      ],\n    ),\n  ],\n  margin: const ChartMargin(top: 24, left: 24, right: 24),\n  tooltip: const ChartTooltipSpec(\n    cursor: false,\n    indicator: ChartIndicator.line,\n    nameKey: \'visitors\',\n    hideLabel: true,\n  ),\n);',
  'chart-line-label':
      'Widget lineLabel(ChartInk ink, ThemeTokens theme) => lineChart(\n  ink.desktopMobile,\n  monthsDesktopMobile,\n  <ChartSeriesSpec>[\n    _lineSeries(\n      ink.slot(1),\n      \'desktop\',\n      CurveType.natural,\n      dot: ChartDot(fill: ink.slot(1)),\n      labels: <ChartLabelList>[\n        ChartLabelList(offset: 12, color: theme.foreground),\n      ],\n    ),\n  ],\n  xAxis: monthAxis(),\n  margin: const ChartMargin(top: 20, left: 12, right: 12),\n  tooltip: const ChartTooltipSpec(\n    cursor: false,\n    indicator: ChartIndicator.line,\n  ),\n);',
  'chart-line-label-custom':
      'Widget lineLabelCustom(ChartInk ink, ThemeTokens theme) => lineChart(\n  ink.browser,\n  browsers,\n  <ChartSeriesSpec>[\n    _lineSeries(\n      ink.slot(2),\n      \'visitors\',\n      CurveType.natural,\n      dot: ChartDot(fill: ink.slot(2)),\n      labels: <ChartLabelList>[\n        ChartLabelList(\n          dataKey: \'browser\',\n          offset: 12,\n          color: theme.foreground,\n          formatter: _browserLabelOf,\n        ),\n      ],\n    ),\n  ],\n  margin: const ChartMargin(top: 24, left: 24, right: 24),\n  tooltip: const ChartTooltipSpec(\n    cursor: false,\n    indicator: ChartIndicator.line,\n    nameKey: \'visitors\',\n    hideLabel: true,\n  ),\n);',
  'chart-line-interactive':
      'Widget lineInteractive(BuildContext context, ChartInk ink) {\n  final String active = SeriesScope.of(context);\n  return plot(\n    ink.desktopMobile.plus(<String, ChartSeries>{\n      \'views\': const ChartSeries(label: \'Page Views\'),\n    }),\n    CartesianChart(\n      data: dailyVisits,\n      margin: const ChartMargin(left: 12, right: 12),\n      grid: const ChartGrid(vertical: false),\n      xAxis: const ChartAxis(\n        dataKey: \'date\',\n        tickLine: false,\n        axisLine: false,\n        tickMargin: 8,\n        minTickGap: 32,\n        tickFormatter: shortDate,\n      ),\n      tooltip: ChartTooltipSpec(\n        nameKey: \'views\',\n        labelFormatter: shortDateYearLabel,\n        // `className="w-40"`.\n        width: space(40),\n      ),\n      series: <ChartSeriesSpec>[\n        _lineSeries(seriesColour(ink, active), active, CurveType.monotone),\n      ],\n    ),\n  );\n}',
  'chart-pie-simple':
      'Widget pieSimple(ChartInk ink) => plot(\n  ink.browser,\n  PieChart(\n    pies: <PieSpec>[_browserPie(ink)],\n    tooltip: const ChartTooltipSpec(cursor: false, hideLabel: true),\n  ),\n);',
  'chart-pie-separator-none':
      'Widget pieSeparatorNone(ChartInk ink) => plot(\n  ink.browser,\n  PieChart(\n    pies: <PieSpec>[_browserPie(ink, strokeWidth: 0)],\n    tooltip: const ChartTooltipSpec(cursor: false, hideLabel: true),\n  ),\n);',
  'chart-pie-label':
      'Widget pieLabel(ChartInk ink, ThemeTokens theme) => plot(\n  ink.browser,\n  PieChart(\n    pies: <PieSpec>[_browserPie(ink, outsideLabel: true)],\n    labelColor: theme.foreground,\n    tooltip: const ChartTooltipSpec(hideLabel: true),\n  ),\n);',
  'chart-pie-label-custom':
      'Widget pieLabelCustom(ChartInk ink, ThemeTokens theme) => plot(\n  ink.browser,\n  PieChart(\n    pies: <PieSpec>[\n      _browserPie(\n        ink,\n        outsideLabel: true,\n        labelLine: false,\n        labelBuilder: (Map<String, Object?> row) =>\n            chartNumber(row[\'visitors\']! as num),\n      ),\n    ],\n    labelColor: theme.foreground,\n    tooltip: const ChartTooltipSpec(nameKey: \'visitors\', hideLabel: true),\n  ),\n);',
  'chart-pie-label-list':
      'Widget pieLabelList(ChartInk ink) => plot(\n  ink.browser,\n  PieChart(\n    pies: <PieSpec>[_browserPie(ink, chipLabelKey: \'browser\')],\n    tooltip: const ChartTooltipSpec(nameKey: \'visitors\', hideLabel: true),\n  ),\n);',
  'chart-pie-legend':
      'Widget pieLegend(ChartInk ink) => plot(\n  ink.browser,\n  PieChart(\n    pies: <PieSpec>[_browserPie(ink)],\n    legend: const ChartLegendSpec(\n      nameKey: \'browser\',\n      wrap: true,\n      // `-translate-y-2`.\n      offset: 8,\n    ),\n  ),\n);',
  'chart-pie-donut':
      'Widget pieDonut(ChartInk ink) => plot(\n  ink.browser,\n  PieChart(\n    pies: <PieSpec>[_browserPie(ink, innerRadius: 60)],\n    tooltip: const ChartTooltipSpec(cursor: false, hideLabel: true),\n  ),\n);',
  'chart-pie-donut-active':
      'Widget pieDonutActive(ChartInk ink) => plot(\n  ink.browser,\n  PieChart(\n    pies: <PieSpec>[\n      _browserPie(\n        ink,\n        innerRadius: 60,\n        strokeWidth: 5,\n        activeIndex: 0,\n        activeGrow: 10,\n      ),\n    ],\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      defaultIndex: 0,\n      hideLabel: true,\n    ),\n  ),\n);',
  'chart-pie-donut-text':
      'Widget pieDonutText(ChartInk ink) {\n  final int total = _pieDonutTextData.fold<int>(\n    0,\n    (int acc, Map<String, Object?> row) => acc + (row[\'visitors\']! as int),\n  );\n  return plot(\n    ink.browser,\n    PieChart(\n      pies: <PieSpec>[\n        _browserPie(\n          ink,\n          innerRadius: 60,\n          strokeWidth: 5,\n          data: _pieDonutTextData,\n        ),\n      ],\n      centerLabel: (BuildContext context) =>\n          donutCentre(context, chartNumber(total), \'Visitors\'),\n      tooltip: const ChartTooltipSpec(cursor: false, hideLabel: true),\n    ),\n  );\n}',
  'chart-pie-stacked':
      'Widget pieStacked(ChartInk ink) => plot(\n  ink.pieMonths,\n  PieChart(\n    pies: <PieSpec>[\n      PieSpec(\n        data: ink.rows(pieMonthsDesktop),\n        dataKey: \'desktop\',\n        nameKey: \'month\',\n        outerRadius: 60,\n      ),\n      PieSpec(\n        data: ink.rows(pieMonthsMobile),\n        dataKey: \'mobile\',\n        nameKey: \'month\',\n        innerRadius: 70,\n        outerRadius: 90,\n      ),\n    ],\n    tooltip: const ChartTooltipSpec(\n      labelKey: \'visitors\',\n      nameKey: \'month\',\n      indicator: ChartIndicator.line,\n    ),\n  ),\n);',
  'chart-pie-interactive':
      'Widget pieInteractive(BuildContext context, ChartInk ink, int activeIndex) =>\n    plot(\n      ink.pieMonths,\n      PieChart(\n        pies: <PieSpec>[\n          PieSpec(\n            data: ink.rows(pieMonthsDesktop),\n            dataKey: \'desktop\',\n            nameKey: \'month\',\n            innerRadius: 60,\n            strokeWidth: 5,\n            activeIndex: activeIndex,\n            activeGrow: 10,\n            activeRing: true,\n          ),\n        ],\n        centerLabel: (BuildContext context) => donutCentre(\n          context,\n          chartNumber(pieMonthsDesktop[activeIndex][\'desktop\']! as num),\n          \'Visitors\',\n        ),\n        tooltip: ChartTooltipSpec(\n          cursor: false,\n          defaultIndex: activeIndex,\n          hideLabel: true,\n        ),\n      ),\n    );',
  'chart-radar-default':
      'Widget radarDefault(ChartInk ink) => radarChart(\n  ink.desktop,\n  radarMonths,\n  <RadarSpec>[_radar(ink.slot(1), \'desktop\', fillOpacity: 0.6)],\n);',
  'chart-radar-dots':
      'Widget radarDots(ChartInk ink) => radarChart(\n  ink.desktop,\n  radarMonths,\n  <RadarSpec>[\n    _radar(ink.slot(1), \'desktop\', fillOpacity: 0.6, dot: const ChartDotSpec()),\n  ],\n);',
  'chart-radar-lines-only':
      'Widget radarLinesOnly(ChartInk ink) =>\n    radarChart(ink.desktopMobile, _radarLinesOnlyData, <RadarSpec>[\n      _radar(\n        ink.slot(1),\n        \'desktop\',\n        fillOpacity: 0,\n        stroke: ink.slot(1),\n        strokeWidth: 2,\n      ),\n      _radar(\n        ink.slot(2),\n        \'mobile\',\n        fillOpacity: 0,\n        stroke: ink.slot(2),\n        strokeWidth: 2,\n      ),\n    ], grid: const PolarGrid(radialLines: false));',
  'chart-radar-label-custom':
      'Widget radarLabelCustom(ChartInk ink) => radarChart(\n  ink.desktopMobile,\n  monthsDesktopMobile,\n  <RadarSpec>[\n    _radar(ink.slot(1), \'desktop\', fillOpacity: 0.6),\n    _radar(ink.slot(2), \'mobile\'),\n  ],\n  angleAxis: const PolarAngleAxis(\n    dataKey: \'month\',\n    tickBuilder: _radarCustomTick,\n  ),\n  margin: const ChartMargin(top: 10, right: 10, bottom: 10, left: 10),\n);',
  'chart-radar-grid-custom':
      'Widget radarGridCustom(ChartInk ink) => radarChart(\n  ink.desktop,\n  radarMonths,\n  <RadarSpec>[_radar(ink.slot(1), \'desktop\', fillOpacity: 0.6)],\n  grid: const PolarGrid(radialLines: false, polarRadius: <double>[90]),\n);',
  'chart-radar-grid-none':
      'Widget radarGridNone(ChartInk ink) => radarChart(\n  ink.desktop,\n  radarMonths,\n  <RadarSpec>[\n    _radar(ink.slot(1), \'desktop\', fillOpacity: 0.6, dot: const ChartDotSpec()),\n  ],\n  grid: null,\n);',
  'chart-radar-grid-circle':
      'Widget radarGridCircle(ChartInk ink) => radarChart(\n  ink.desktop,\n  radarMonths,\n  <RadarSpec>[\n    _radar(ink.slot(1), \'desktop\', fillOpacity: 0.6, dot: const ChartDotSpec()),\n  ],\n  grid: const PolarGrid(gridType: PolarGridType.circle),\n);',
  'chart-radar-grid-circle-no-lines':
      'Widget radarGridCircleNoLines(ChartInk ink) => radarChart(\n  ink.desktop,\n  _radarCircleNoLinesData,\n  <RadarSpec>[\n    _radar(ink.slot(1), \'desktop\', fillOpacity: 0.6, dot: const ChartDotSpec()),\n  ],\n  grid: const PolarGrid(gridType: PolarGridType.circle, radialLines: false),\n);',
  'chart-radar-grid-circle-fill':
      'Widget radarGridCircleFill(ChartInk ink) => radarChart(\n  ink.desktop,\n  radarMonthsFill,\n  <RadarSpec>[_radar(ink.slot(1), \'desktop\', fillOpacity: 0.5)],\n  grid: PolarGrid(\n    gridType: PolarGridType.circle,\n    fills: <Color>[ink.slot(1)],\n    opacity: 0.2,\n  ),\n);',
  'chart-radar-grid-fill':
      'Widget radarGridFill(ChartInk ink) => radarChart(\n  ink.desktop,\n  radarMonthsFill,\n  <RadarSpec>[_radar(ink.slot(1), \'desktop\', fillOpacity: 0.5)],\n  grid: PolarGrid(fills: <Color>[ink.slot(1)], opacity: 0.2),\n);',
  'chart-radar-multiple':
      'Widget radarMultiple(ChartInk ink) =>\n    radarChart(ink.desktopMobile, monthsDesktopMobile, _radarPair(ink));',
  'chart-radar-legend':
      'Widget radarLegend(ChartInk ink) => radarChart(\n  ink.desktopMobile,\n  monthsDesktopMobile,\n  _radarPair(ink),\n  legend: const ChartLegendSpec(),\n  margin: const ChartMargin(top: -40, bottom: -10),\n);',
  'chart-radar-icons':
      'Widget radarIcons(ChartInk ink) => plot(\n  ChartConfig(<String, ChartSeries>{\n    \'desktop\': ChartSeries(\n      label: \'Desktop\',\n      color: ink.slot(1),\n      icon: (BuildContext context) =>\n          const Icon.lucide(Lucide.arrowDownFromLine, size: IconSize.sm),\n    ),\n    \'mobile\': ChartSeries(\n      label: \'Mobile\',\n      color: ink.slot(2),\n      icon: (BuildContext context) =>\n          const Icon.lucide(Lucide.arrowUpFromLine, size: IconSize.sm),\n    ),\n  }),\n  RadarChart(\n    data: monthsDesktopMobile,\n    series: _radarPair(ink),\n    grid: const PolarGrid(),\n    angleAxis: const PolarAngleAxis(dataKey: \'month\'),\n    legend: const ChartLegendSpec(),\n    margin: const ChartMargin(top: -40, bottom: -10),\n  ),\n);',
  'chart-radar-radius':
      'Widget radarRadius(ChartInk ink, ThemeTokens theme) => plot(\n  ink.desktopMobile,\n  RadarChart(\n    data: monthsDesktopMobile,\n    series: _radarPair(ink),\n    grid: const PolarGrid(),\n    angleAxis: null,\n    radiusAxis: PolarRadiusAxis(\n      angle: 60,\n      stroke: theme.foreground,\n      axisLine: false,\n    ),\n  ),\n);',
  'chart-radial-simple':
      'Widget radialSimple(ChartInk ink) => plot(\n  ink.browser,\n  RadialBarChart(\n    data: ink.rows(browsers),\n    innerRadius: 30,\n    outerRadius: 110,\n    series: const <RadialBarSpec>[\n      RadialBarSpec(dataKey: \'visitors\', background: true),\n    ],\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      hideLabel: true,\n      nameKey: \'browser\',\n    ),\n  ),\n);',
  'chart-radial-grid':
      'Widget radialGrid(ChartInk ink) => plot(\n  ink.browser,\n  RadialBarChart(\n    data: ink.rows(browsers),\n    innerRadius: 30,\n    outerRadius: 100,\n    grid: const PolarGrid(gridType: PolarGridType.circle),\n    series: const <RadialBarSpec>[RadialBarSpec(dataKey: \'visitors\')],\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      hideLabel: true,\n      nameKey: \'browser\',\n    ),\n  ),\n);',
  'chart-radial-label':
      'Widget radialLabel(ChartInk ink) => plot(\n  ink.browser,\n  RadialBarChart(\n    data: ink.rows(browsers),\n    startAngle: -90,\n    endAngle: 380,\n    innerRadius: 30,\n    outerRadius: 110,\n    series: const <RadialBarSpec>[\n      RadialBarSpec(\n        dataKey: \'visitors\',\n        background: true,\n        chipLabelKey: \'browser\',\n      ),\n    ],\n    tooltip: const ChartTooltipSpec(\n      cursor: false,\n      hideLabel: true,\n      nameKey: \'browser\',\n    ),\n  ),\n);',
  'chart-radial-text':
      'Widget radialText(ChartInk ink, ThemeTokens theme) => plot(\n  ChartConfig(<String, ChartSeries>{\n    \'visitors\': const ChartSeries(label: \'Visitors\'),\n    \'safari\': ChartSeries(label: \'Safari\', color: ink.slot(2)),\n  }),\n  RadialBarChart(\n    data: ink.rows(_radialTextData),\n    startAngle: 0,\n    endAngle: 250,\n    innerRadius: 80,\n    outerRadius: 110,\n    grid: _radialPlate(theme),\n    series: const <RadialBarSpec>[\n      RadialBarSpec(\n        dataKey: \'visitors\',\n        background: true,\n        cornerRadius: _ringRadius,\n      ),\n    ],\n    radiusAxis: PolarRadiusAxis(\n      tick: false,\n      axisLine: false,\n      centerLabel: (BuildContext context) =>\n          donutCentre(context, chartNumber(200), \'Visitors\'),\n    ),\n  ),\n);',
  'chart-radial-shape':
      'Widget radialShape(ChartInk ink, ThemeTokens theme) => plot(\n  ChartConfig(<String, ChartSeries>{\n    \'visitors\': const ChartSeries(label: \'Visitors\'),\n    \'safari\': ChartSeries(label: \'Safari\', color: ink.slot(2)),\n  }),\n  RadialBarChart(\n    data: ink.rows(_radialShapeData),\n    endAngle: 100,\n    innerRadius: 80,\n    outerRadius: 140,\n    grid: _radialPlate(theme),\n    series: const <RadialBarSpec>[\n      RadialBarSpec(dataKey: \'visitors\', background: true),\n    ],\n    radiusAxis: PolarRadiusAxis(\n      tick: false,\n      axisLine: false,\n      centerLabel: (BuildContext context) =>\n          donutCentre(context, chartNumber(1260), \'Visitors\'),\n    ),\n  ),\n);',
  'chart-radial-stacked':
      'Widget radialStacked(ChartInk ink) {\n  const int total = 1260 + 570;\n  return plot(\n    ink.desktopMobile,\n    RadialBarChart(\n      data: _radialStackedData,\n      endAngle: 180,\n      innerRadius: 80,\n      outerRadius: 130,\n      angleAxis: PolarAngleAxis(\n        tick: false,\n        axisLine: false,\n        domain: (min: 0, max: total.toDouble()),\n      ),\n      radiusAxis: PolarRadiusAxis(\n        tick: false,\n        axisLine: false,\n        centerLabel: (BuildContext context) {\n          final ThemeTokens theme = ThemeScope.of(context);\n          return Column(\n            mainAxisSize: MainAxisSize.min,\n            children: <Widget>[\n              StyledText(\n                chartNumber(total),\n                TextStyles.numberLg,\n                color: theme.foreground,\n              ),\n              SizedBox(height: space(1)),\n              StyledText(\n                \'Visitors\',\n                ChartText.xs,\n                color: theme.mutedForeground,\n              ),\n            ],\n          );\n        },\n      ),\n      series: <RadialBarSpec>[\n        RadialBarSpec(\n          dataKey: \'desktop\',\n          stackId: \'a\',\n          cornerRadius: _stackRadius,\n          fill: ink.slot(1),\n        ),\n        RadialBarSpec(\n          dataKey: \'mobile\',\n          stackId: \'a\',\n          cornerRadius: _stackRadius,\n          fill: ink.slot(2),\n        ),\n      ],\n      tooltip: const ChartTooltipSpec(cursor: false, hideLabel: true),\n    ),\n  );\n}',
  'chart-tooltip-default':
      'Widget tooltipDefault(ChartInk ink) => tooltipChart(\n  ink,\n  ink.sport,\n  const ChartTooltipSpec(cursor: false, defaultIndex: 1),\n);',
  'chart-tooltip-indicator-line':
      'Widget tooltipIndicatorLine(ChartInk ink) => tooltipChart(\n  ink,\n  ink.sport,\n  const ChartTooltipSpec(\n    cursor: false,\n    defaultIndex: 1,\n    indicator: ChartIndicator.line,\n  ),\n);',
  'chart-tooltip-indicator-none':
      'Widget tooltipIndicatorNone(ChartInk ink) => tooltipChart(\n  ink,\n  ink.sport,\n  const ChartTooltipSpec(cursor: false, defaultIndex: 1, hideIndicator: true),\n);',
  'chart-tooltip-label-custom':
      'Widget tooltipLabelCustom(ChartInk ink) => tooltipChart(\n  ink,\n  ink.sport.plus(<String, ChartSeries>{\n    \'activities\': const ChartSeries(label: \'Activities\'),\n  }),\n  const ChartTooltipSpec(\n    cursor: false,\n    defaultIndex: 1,\n    labelKey: \'activities\',\n    indicator: ChartIndicator.line,\n  ),\n);',
  'chart-tooltip-label-formatter':
      'Widget tooltipLabelFormatter(ChartInk ink) => tooltipChart(\n  ink,\n  ink.sport,\n  const ChartTooltipSpec(\n    cursor: false,\n    defaultIndex: 1,\n    labelFormatter: _longDateLabel,\n  ),\n);',
  'chart-tooltip-label-none':
      'Widget tooltipLabelNone(ChartInk ink) => tooltipChart(\n  ink,\n  ink.sport,\n  const ChartTooltipSpec(\n    cursor: false,\n    defaultIndex: 1,\n    hideIndicator: true,\n    hideLabel: true,\n  ),\n);',
  'chart-tooltip-formatter':
      'Widget tooltipFormatter(ChartInk ink) => tooltipChart(\n  ink,\n  ink.sport,\n  ChartTooltipSpec(\n    cursor: false,\n    defaultIndex: 1,\n    hideLabel: true,\n    formatter: (BuildContext context, ChartTooltipItem item, int index) =>\n        _KcalRow(item: item),\n  ),\n);',
  'chart-tooltip-icons':
      'Widget tooltipIcons(ChartInk ink) => tooltipChart(\n  ink,\n  ChartConfig(<String, ChartSeries>{\n    \'running\': ChartSeries(\n      label: \'Running\',\n      color: ink.slot(1),\n      icon: (BuildContext context) => const Icon.lucide(\n        Lucide.footprints,\n        size: IconSize.xs,\n        tone: IconTone.muted,\n      ),\n    ),\n    \'swimming\': ChartSeries(\n      label: \'Swimming\',\n      color: ink.slot(2),\n      icon: (BuildContext context) => const Icon.lucide(\n        Lucide.wavesHorizontal,\n        size: IconSize.xs,\n        tone: IconTone.muted,\n      ),\n    ),\n  }),\n  const ChartTooltipSpec(cursor: false, defaultIndex: 1, hideLabel: true),\n);',
  'chart-tooltip-advanced':
      'Widget tooltipAdvanced(ChartInk ink) => tooltipChart(\n  ink,\n  ink.sport,\n  ChartTooltipSpec(\n    cursor: false,\n    defaultIndex: 1,\n    hideLabel: true,\n    // `className="w-44"`, 176px, the nearest rung of the same scale\n    // `min-w-32` uses, close enough that the fixed-width Total row does not\n    // reflow between the two hovered series.\n    width: space(44),\n    formatter: (BuildContext context, ChartTooltipItem item, int index) =>\n        _AdvancedRow(item: item, index: index, ink: ink),\n  ),\n);',
};
